package com.eldercare.app.model

enum class EventType {
    NETWORK_CHANGED,
    WIFI_STATE_CHANGED,
    WIFI_CONNECTION_CHANGED,
    AIRPLANE_MODE_CHANGED,
    RINGER_MODE_CHANGED,
    BATTERY_LOW,
    BATTERY_OKAY,
    CHARGING_STATE_CHANGED,
    LOCATION_SERVICE_CHANGED
}
